"""Built-in style library with genre and mood definitions."""

from __future__ import annotations

from composer.styles.style import Style


class StyleLibrary:
    """Collection of pre-defined styles for various genres."""

    STYLES: dict[str, Style] = {
        "orchestral": Style(
            name="orchestral",
            preferred_scales=["major", "natural_minor", "harmonic_minor"],
            use_seventh_chords=False,
            melody_contour="arch",
            melody_density=0.6,
            melody_range_octaves=2,
            bass_style="root",
            accompaniment_style="pad",
            drum_genre="orchestral",
            drum_intensity=0.4,
            use_drums=True,
            dynamic_curve="arc",
            base_velocity=80,
            typical_sections=["intro", "theme_a", "theme_b", "theme_a", "climax", "outro"],
            measures_per_section=8,
        ),
        "cinematic": Style(
            name="cinematic",
            preferred_scales=["natural_minor", "harmonic_minor", "major"],
            use_seventh_chords=True,
            melody_contour="climbing",
            melody_density=0.5,
            melody_range_octaves=2,
            bass_style="root",
            accompaniment_style="pad",
            drum_genre="cinematic",
            drum_intensity=0.6,
            dynamic_curve="crescendo",
            base_velocity=70,
            typical_sections=["intro", "buildup", "theme", "development", "climax", "resolution"],
            measures_per_section=8,
        ),
        "electronic": Style(
            name="electronic",
            preferred_scales=["natural_minor", "pentatonic_minor", "dorian"],
            use_seventh_chords=False,
            melody_contour="wave",
            melody_density=0.8,
            bass_style="pumping",
            accompaniment_style="arpeggio",
            drum_genre="electronic",
            drum_intensity=0.9,
            dynamic_curve="wave",
            base_velocity=90,
            typical_sections=["intro", "buildup", "drop", "breakdown", "buildup", "drop", "outro"],
            measures_per_section=8,
        ),
        "jazz": Style(
            name="jazz",
            preferred_scales=["major", "dorian", "mixolydian", "blues"],
            use_seventh_chords=True,
            use_extended_chords=True,
            chromatic_passing_tones=True,
            swing=0.6,
            melody_contour="wave",
            melody_density=0.7,
            melody_variation=0.5,
            bass_style="walking",
            accompaniment_style="block",
            drum_genre="jazz",
            drum_intensity=0.5,
            dynamic_curve="wave",
            base_velocity=75,
            typical_sections=["head", "solo_a", "solo_b", "head", "outro"],
            measures_per_section=8,
        ),
        "rock": Style(
            name="rock",
            preferred_scales=["pentatonic_minor", "natural_minor", "blues"],
            melody_contour="arch",
            melody_density=0.7,
            bass_style="root",
            accompaniment_style="strum",
            drum_genre="rock",
            drum_intensity=0.8,
            dynamic_curve="arc",
            base_velocity=90,
            typical_sections=["intro", "verse", "chorus", "verse", "chorus", "bridge", "chorus", "outro"],
            measures_per_section=8,
        ),
        "metal": Style(
            name="metal",
            preferred_scales=["natural_minor", "phrygian", "harmonic_minor"],
            melody_contour="falling",
            melody_density=0.8,
            bass_style="root",
            accompaniment_style="tremolo",
            drum_genre="metal",
            drum_intensity=0.95,
            dynamic_curve="flat",
            base_velocity=110,
            typical_sections=["intro", "verse", "chorus", "verse", "chorus", "breakdown", "chorus", "outro"],
            measures_per_section=8,
        ),
        "classical": Style(
            name="classical",
            preferred_scales=["major", "natural_minor", "harmonic_minor"],
            use_seventh_chords=True,
            melody_contour="arch",
            melody_density=0.6,
            melody_variation=0.3,
            bass_style="root",
            accompaniment_style="alberti",
            drum_genre="classical",
            drum_intensity=0.0,
            use_drums=False,
            dynamic_curve="arc",
            base_velocity=75,
            typical_sections=["exposition", "development", "recapitulation", "coda"],
            measures_per_section=16,
        ),
        "ambient": Style(
            name="ambient",
            preferred_scales=["major", "lydian", "dorian", "pentatonic_major"],
            melody_contour="plateau",
            melody_density=0.3,
            melody_range_octaves=1,
            bass_style="pedal",
            accompaniment_style="pad",
            drum_genre="ambient",
            drum_intensity=0.2,
            dynamic_curve="wave",
            base_velocity=55,
            typical_sections=["intro", "atmosphere_a", "atmosphere_b", "atmosphere_a", "outro"],
            measures_per_section=16,
        ),
        "folk": Style(
            name="folk",
            preferred_scales=["major", "mixolydian", "dorian"],
            melody_contour="wave",
            melody_density=0.65,
            bass_style="root",
            accompaniment_style="strum",
            drum_genre="folk",
            drum_intensity=0.5,
            dynamic_curve="flat",
            base_velocity=75,
            typical_sections=["intro", "verse", "chorus", "verse", "chorus", "verse", "chorus", "outro"],
            measures_per_section=8,
        ),
        "blues": Style(
            name="blues",
            preferred_scales=["blues", "pentatonic_minor", "mixolydian"],
            use_seventh_chords=True,
            swing=0.4,
            melody_contour="falling",
            melody_density=0.6,
            melody_variation=0.4,
            bass_style="walking",
            accompaniment_style="block",
            drum_genre="blues",
            drum_intensity=0.6,
            dynamic_curve="wave",
            base_velocity=80,
            typical_sections=["intro", "verse", "verse", "verse", "turnaround"],
            measures_per_section=12,
        ),
        "pop": Style(
            name="pop",
            preferred_scales=["major", "natural_minor"],
            melody_contour="arch",
            melody_density=0.7,
            bass_style="root",
            accompaniment_style="arpeggio",
            drum_genre="pop",
            drum_intensity=0.7,
            dynamic_curve="arc",
            base_velocity=80,
            typical_sections=["intro", "verse", "chorus", "verse", "chorus", "bridge", "chorus", "outro"],
            measures_per_section=8,
        ),
        "rnb": Style(
            name="rnb",
            preferred_scales=["major", "dorian", "pentatonic_minor"],
            use_seventh_chords=True,
            use_extended_chords=True,
            syncopation=0.5,
            melody_contour="wave",
            melody_density=0.6,
            bass_style="root",
            accompaniment_style="arpeggio",
            drum_genre="rnb",
            drum_intensity=0.6,
            dynamic_curve="wave",
            base_velocity=75,
            typical_sections=["intro", "verse", "chorus", "verse", "chorus", "bridge", "chorus", "outro"],
            measures_per_section=8,
        ),
        "celtic": Style(
            name="celtic",
            preferred_scales=["mixolydian", "dorian", "pentatonic_major", "major"],
            melody_contour="wave",
            melody_density=0.7,
            melody_variation=0.4,
            bass_style="root",
            accompaniment_style="strum",
            drum_genre="celtic",
            drum_intensity=0.6,
            dynamic_curve="arc",
            base_velocity=80,
            typical_sections=["intro", "theme_a", "theme_b", "theme_a", "theme_b", "climax", "outro"],
            measures_per_section=8,
        ),
        "middle_eastern": Style(
            name="middle_eastern",
            preferred_scales=["phrygian_dominant", "double_harmonic", "harmonic_minor"],
            melody_contour="wave",
            melody_density=0.75,
            melody_variation=0.5,
            melody_range_octaves=2,
            bass_style="pedal",
            accompaniment_style="arpeggio",
            drum_genre="middle_eastern",
            drum_intensity=0.7,
            dynamic_curve="arc",
            base_velocity=80,
            typical_sections=["intro", "theme", "development", "theme", "climax", "outro"],
            measures_per_section=8,
        ),
        "wuxia": Style(
            name="wuxia",
            preferred_scales=["pentatonic_major", "pentatonic_minor", "hirajoshi"],
            melody_contour="climbing",
            melody_density=0.6,
            melody_variation=0.4,
            melody_range_octaves=2,
            bass_style="pedal",
            accompaniment_style="arpeggio",
            drum_genre="wuxia",
            drum_intensity=0.4,
            dynamic_curve="arc",
            base_velocity=70,
            typical_sections=["intro", "theme_a", "development", "theme_b", "climax", "resolution"],
            measures_per_section=8,
        ),
        "fantasy": Style(
            name="fantasy",
            preferred_scales=["lydian", "major", "natural_minor", "harmonic_minor"],
            use_seventh_chords=True,
            melody_contour="arch",
            melody_density=0.6,
            melody_range_octaves=2,
            bass_style="root",
            accompaniment_style="pad",
            drum_genre="fantasy",
            drum_intensity=0.5,
            dynamic_curve="arc",
            base_velocity=75,
            typical_sections=["intro", "theme", "journey", "theme", "climax", "resolution"],
            measures_per_section=8,
        ),
        "heavenly": Style(
            name="heavenly",
            preferred_scales=["lydian", "major", "pentatonic_major"],
            melody_contour="ascending",
            melody_density=0.4,
            melody_range_octaves=2,
            bass_style="pedal",
            accompaniment_style="pad",
            drum_genre="heavenly",
            drum_intensity=0.2,
            use_drums=True,
            dynamic_curve="crescendo",
            base_velocity=60,
            typical_sections=["intro", "ascension", "revelation", "ascension", "transcendence"],
            measures_per_section=12,
        ),
    }

    @classmethod
    def get(cls, genre: str) -> Style:
        """Get a style by genre name."""
        return cls.STYLES.get(genre, cls.STYLES["cinematic"])

    @classmethod
    def list_styles(cls) -> list[str]:
        return sorted(cls.STYLES.keys())
